import type { Metadata } from "next";
import { Header } from "./_components/header/header";
import { Footer } from "./_components/footer/footer";
import "./globals.css";
import Product from "./Product/Product";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, 
}: {
  children: React.ReactNode;  
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen flex flex-col justify-between">
          <div>
            <Header />
          </div>
<Product/>
          <Footer />
        </div>
      </body>
    </html>
  );
}
